In [30]:
print('Acceclerator Exercise 01')

print('-Multiply 2 3x3 Matrices')
print('-This Matrices should be Random')

import numpy as np

a = np.random.rand(3,3) #Random
b = np.random.rand(3,3) #Random

print(a)
print(b)

def func1(): 
    c = a * b  #Multiply of the Random Matrices
    print(c) #Result
func1()


Acceclerator Exercise 01
-Multiply 2 3x3 Matrices
-This Matrices should be Random
[[0.50104865 0.79919541 0.63104782]
 [0.06145472 0.18922738 0.143147  ]
 [0.72685732 0.76918582 0.6221559 ]]
[[0.73778913 0.40487381 0.64239606]
 [0.53909659 0.31142142 0.57614996]
 [0.26772401 0.34331241 0.69602801]]
[[0.36966825 0.32357329 0.40538264]
 [0.03313003 0.05892946 0.08247414]
 [0.19459716 0.26407103 0.43303793]]
